package autoreg

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/bytedance/sonic"

	"loopforge/pkg/model"
)

// ToolHandlerTyped is a typed tool handler that receives pre-parsed parameters.
type ToolHandlerTyped[T any] func(ctx context.Context, params T) (string, error)

// ToolOption configures the ToolInfo returned by NewToolFromStruct.
type ToolOption func(*model.ToolInfo)

// WithParameters overrides the auto-generated Parameters with a custom map.
//
// Deprecated: Parameters are now auto-generated from struct tags.
// Passing custom Parameters may conflict with the auto-wrapped Handle
// (the Handle unmarshals into struct T, but Parameters advertise different fields).
// This option is provided for migration only and will be removed in a future version.
func WithParameters(params map[string]interface{}) ToolOption {
	return func(info *model.ToolInfo) {
		slog.Warn("WithParameters is deprecated: " +
			"Parameters are auto-generated from struct tags. " +
			"Custom Parameters may conflict with the auto-wrapped Handle. " +
			"This option will be removed in a future version.")
		info.Parameters = params
	}
}

// NewToolFromStruct creates a *model.ToolInfo from a typed handler.
//   - name / description: tool name + description (same as ToolInfo fields).
//   - handler: typed handler that receives auto-parsed params T.
//   - opts: optional ToolOption values (e.g. WithParameters for migration).
//   - T must be a struct with json tags on exported fields.
//
// The returned ToolInfo has:
//   - Parameters auto-generated by SchemaFromStruct[T]()
//   - Handle auto-wrapping: unmarshal argumentsJSON → T → call handler
//
// If no ToolOption is provided, Parameters are auto-generated from struct tags.
// WithParameters overrides the auto-generated Parameters with a deprecation warning.
func NewToolFromStruct[T any](name, description string, handler ToolHandlerTyped[T], opts ...ToolOption) *model.ToolInfo {
	info := &model.ToolInfo{
		Name:        name,
		Description: description,
		Parameters:  SchemaFromStruct[T](),
		Handle: func(ctx context.Context, argumentsJSON string) (string, error) {
			var params T
			if err := sonic.UnmarshalString(argumentsJSON, &params); err != nil {
				return "", fmt.Errorf("parse %q arguments: %w", name, err)
			}
			return handler(ctx, params)
		},
	}
	for _, o := range opts {
		if o != nil {
			o(info)
		}
	}
	return info
}
