package plan

import "time"

// Plan is a structured execution plan generated by an agent and owned by the Runner.
type Plan struct {
	ID          string     `json:"id"`
	Title       string     `json:"title"`
	Description string     `json:"description,omitempty"`
	Steps       []PlanStep `json:"steps"`
	CreatedAt   time.Time  `json:"created_at"`
}

// PlanStep represents one step in a plan.
type PlanStep struct {
	ID          string         `json:"id"`
	Description string         `json:"description"`
	AssignedTo  string         `json:"assigned_to"`
	DependsOn   []string       `json:"depends_on,omitempty"`
	Status      PlanStepStatus `json:"status"`
	Result      string         `json:"result,omitempty"`
	StartedAt   *time.Time     `json:"started_at,omitempty"`
	CompletedAt *time.Time     `json:"completed_at,omitempty"`
}

// PlanStepStatus enumerates step lifecycle states.
type PlanStepStatus string

const (
	PlanStepPending    PlanStepStatus = "pending"
	PlanStepInProgress PlanStepStatus = "in_progress"
	PlanStepCompleted  PlanStepStatus = "completed"
	PlanStepFailed     PlanStepStatus = "failed"
	PlanStepSkipped    PlanStepStatus = "skipped"
)

// isTerminal returns true if the status is a terminal (non-reversible) state.
func isTerminal(s PlanStepStatus) bool {
	return s == PlanStepCompleted || s == PlanStepFailed || s == PlanStepSkipped
}
